services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: superSecretPassword # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: bonappetitum